name: scrape
on:
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Installed package list
        run: apt list --installed
      - name: Update Linux
        run: sudo apt-get update
      - name: Remove Chrome
        run: sudo apt purge google-chrome-stable
      
      - name: Install software
        run: sudo apt install -y chromium-browser
      - name: Install all necessary packages
        run: pip install requests beautifulsoup4 pandas webdriver-manager selenium==3.8.1
      - name: Wget ChromeDriver
        run: wget https://chromedriver.storage.googleapis.com/index.html?path=101.0.4951.41/
      - name: Run the scraping script
        run: python scraper.py

